# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

# ---- llm ----
# model: openai:gpt-4o-mini
model: gemini:gemini-2.5-pro-exp-03-25

# ---- behavior ----
stream: true                     # Controls whether to use the stream-style API.
save: true                       # Indicates whether to persist the message
keybindings: vi               # Choose keybinding style (emacs, vi)
wrap: no                         # Controls text wrapping (no, auto, <max-width>)
wrap_code: false                 # Enables or disables wrapping of code blocks

# ---- apperence ----
highlight: true                  # Controls syntax highlighting

clients:
- type: claude
  api_key: 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
- type: openai
  api_key: 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
- type: gemini
  api_key: AIzaSyDH9bhCZV0-K2_30k6UUCkGxIS9c-zBnlU
